export enum landlordPageEnum {
  GET_HOUSE_REQUEST = 'APP/HOST_HOUSE_LIST/GET_HOUSE_REQUEST',
  GET_HOUSE_SUCCESS = 'APP/HOST_HOUSE_LIST/GET_HOUSE_SUCCESS',
  GET_HOUSE_FAILURE = 'APP/HOST_HOUSE_LIST/GET_HOUSE_FAILURE',

  DELETE_HOUSE_REQUEST = 'APP/HOST_HOUSE_LIST/DELETE_HOUSE_REQUEST',
  DELETE_HOUSE_SUCCESS = 'APP/HOST_HOUSE_LIST/DELETE_HOUSE_SUCCESS',
  DELETE_HOUSE_FAILURE = 'APP/HOST_HOUSE_LIST/DELETE_HOUSE_FAILURE',

  CLEAR_HOST_HOUSE_STATE = 'APP/HOST/HOST_ROOM_CREATE_STATE/CLEAR_HOST_HOUSE_STATE',
}
