export enum settingAccountPageEnum {
  CHANGE_PASSWORD_REQUEST = 'APP/SETTING_ACCOUNT/CHANGE_PASSWORD_REQUEST',
  CHANGE_PASSWORD_SUCCESS = 'APP/ASETTING_ACCOUNT/CHANGE_PASSWORD_SUCCESS',
  CHANGE_PASSWORD_FAILURE = 'APP/SETTING_ACCOUNT/CHANGE_PASSWORD_FAILURE',

  UPDATE_ROLE_REQUEST = 'APP/SETTING_ACCOUNT/UPDATE_ROLE_REQUEST',
  UPDATE_ROLE_SUCCESS = 'APP/ASETTING_ACCOUNT/UPDATE_ROLE_SUCCESS',
  UPDATE_ROLE_FAILURE = 'APP/SETTING_ACCOUNT/UPDATE_ROLE_FAILURE',
  
  CLEAR_SETTING_STATE = 'APP/SETTING_ACCOUNT/CLEAR_SETTING_STATE',
}
