export enum adminReportPageEnum {
    GET_REPORT_POST_REQUEST = 'APP/DETAIL_ROOM_PAGE/GET_REPORT_POST_REQUEST',
    GET_REPORT_POST_SUCCESS = 'APP/DETAIL_ROOM_PAGE/GET_REPORT_POST_SUCCESS',
    GET_REPORT_POST_FAILURE = 'APP/DETAIL_ROOM_PAGE/GET_REPORT_POST_FAILURE',

    CLEAR_STATE_REPORT = 'APP/DETAIL_ROOM_PAGE/CLEAR_STATE_REPORT',

}
