export enum adminPageEnum {
  LOAD_DATA_USER_REQUEST = 'APP/ADMIN_PAGE/LOAD_DATA_USER_REQUEST',
  LOAD_DATA_USER_SUCCESS = 'APP/ADMIN_PAGE/LOAD_DATA_USER_SUCCESS',
  LOAD_DATA_USER_FAILURE = 'APP/ADMIN_PAGE/LOAD_DATA_USER_FAILURE',
}
