export enum hostDashboardPageEnum {
  HOST_DASHBOARD_REQUEST = 'APP/ADMIN_DASHBOARD_PAGE/HOST_DASHBOARD_REQUEST',
  HOST_DASHBOARD_SUCCESS = 'APP/ADMIN_DASHBOARD_PAGE/HOST_DASHBOARD_SUCCESS',
  HOST_DASHBOARD_FAILURE = 'APP/ADMIN_DASHBOARD_PAGE/HOST_DASHBOARD_FAILURE',


  HOST_DASHBOARD_DATA_REQUEST = 'APP/ADMIN_DASHBOARD_PAGE/HOST_DASHBOARD_DATA_REQUEST',
  HOST_DASHBOARD_DATA_SUCCESS = 'APP/ADMIN_DASHBOARD_PAGE/HOST_DASHBOARD_DATA_SUCCESS',
  HOST_DASHBOARD_DATA_FAILURE = 'APP/ADMIN_DASHBOARD_PAGE/HOST_DASHBOARD_DATA_FAILURE',
}
