export enum adminFeedbackPageEnum {
  DELETE_FEEDBACK_REQUEST = 'APP/ADMIN_PAGE/DELETE_FEEDBACK_REQUEST',
  DELETE_FEEDBACK_SUCCESS = 'APP/ADMIN_PAGE/DELETE_FEEDBACK_SUCCESS',
  DELETE_FEEDBACK_FAILURE = 'APP/ADMIN_PAGE/DELETE_FEEDBACK_FAILURE',

  CLEAR_FEEDBACK = 'APP/ADMIN_PAGE/CLEAR_FEEDBACK',
}
