export enum userInformationEnum {
  UPDATE_USER_REQUEST = 'UPDATE/USER_REQUEST',
  UPDATE_USER_SUCCESS = 'UPDATE/USER_SUCCESS',
  UPDATE_USER_FAILURE = 'UPDATE/USER_FAILURE',

  UPDATE_ROLE_USER_REQUEST = 'UPDATE/ROLE_USER_REQUEST',
  UPDATE_ROLE_USER_SUCCESS = 'UPDATE/ROLE_USER_SUCCESS',
  UPDATE_ROLE_USER_FAILURE = 'UPDATE/ROLE_USER_FAILURE',
}
