export enum hostRoomGetPageEnum {
  GET_ROOM_REQUEST = 'APP/HOST_HOUSE_LIST/GET_ROOM_REQUEST',
  GET_ROOM_SUCCESS = 'APP/HOST_HOUSE_LIST/GET_ROOM_SUCCESS',
  GET_ROOM_FAILURE = 'APP/HOST_HOUSE_LIST/GET_ROOM_FAILURE',
}
