export enum adminDashboardPageEnum {
  ADMIN_DASHBOARD_REQUEST = 'APP/ADMIN_DASHBOARD_PAGE/ADMIN_DASHBOARD_REQUEST',
  ADMIN_DASHBOARD_SUCCESS = 'APP/ADMIN_DASHBOARD_PAGE/ADMIN_DASHBOARD_SUCCESS',
  ADMIN_DASHBOARD_FAILURE = 'APP/ADMIN_DASHBOARD_PAGE/ADMIN_DASHBOARD_FAILURE',


  ADMIN_DASHBOARD_DATA_REQUEST = 'APP/ADMIN_DASHBOARD_PAGE/ADMIN_DASHBOARD_DATA_REQUEST',
  ADMIN_DASHBOARD_DATA_SUCCESS = 'APP/ADMIN_DASHBOARD_PAGE/ADMIN_DASHBOARD_DATA_SUCCESS',
  ADMIN_DASHBOARD_DATA_FAILURE = 'APP/ADMIN_DASHBOARD_PAGE/ADMIN_DASHBOARD_DATA_FAILURE',
}
