export enum hostRoomGetPageEnum {
  GET_ROOM_REQUEST = 'APP/HOST_HOUSE_LIST/GET_ROOM_REQUEST',
  GET_ROOM_SUCCESS = 'APP/HOST_HOUSE_LIST/GET_ROOM_SUCCESS',
  GET_ROOM_FAILURE = 'APP/HOST_HOUSE_LIST/GET_ROOM_FAILURE',

  DELETE_ROOM_REQUEST = 'APP/HOST_HOUSE_LIST/DELETE_ROOM_REQUEST',
  DELETE_ROOM_SUCCESS = 'APP/HOST_HOUSE_LIST/DELETE_ROOM_SUCCESS',
  DELETE_ROOM_FAILURE = 'APP/HOST_HOUSE_LIST/DELETE_ROOM_FAILURE',

  CLEAR_HOST_ROOM_STATE = 'APP/HOST/HOST_ROOM_CREATE_STATE/CLEAR_HOST_ROOM_STATE',
}
