export enum authenticationSignUpEnum {
  SIGN_UP_REQUEST = 'APP/AUTHENTICATION/SIGN_UP_REQUEST',
  SIGN_UP_SUCCESS = 'APP/AUTHENTICATION/SIGN_UP_SUCCESS',
  SIGN_UP_FAILURE = 'APP/AUTHENTICATION/SIGN_UP_FAILURE',

  SIGN_UP_WITH_GG_REQUEST = 'APP/AUTHENTICATION/SIGN_UP_WITH_GG_REQUEST',
  SIGN_UP_WITH_GG_SUCCESS = 'APP/AUTHENTICATION/SIGN_UP_WITH_GG_SUCCESS',
  SIGN_UP_WITH_GG_FAILURE = 'APP/AUTHENTICATION/SIGN_UP_WITH_GG_FAILURE',

  CLEAR_SIGN_UP_STATE = 'APP/AUTHENTICATION/SIGN_UP_CLEAR_STATE',
}
