export enum roomTenantPageEnum {
  LOAD_DATA_CUSTOMER_REQUEST = 'APP/LANDLORD_PAGE/LOAD_DATA_CUSTOMER_REQUEST',
  LOAD_DATA_CUSTOMER_SUCCESS = 'APP/LANDLORD_PAGE/LOAD_DATA_CUSTOMER_SUCCESS',
  LOAD_DATA_CUSTOMER_FAILURE = 'APP/LANDLORD_PAGE/LOAD_DATA_CUSTOMER_FAILURE',
}
