export enum authenticationVerifyAccountEnum {
  VERIFY_ACCOUNT_REQUEST = 'APP/AUTHENTICATION/VERIFY_ACCOUNT_REQUEST',
  VERIFY_ACCOUNT_SUCCESS = 'APP/AUTHENTICATION/VERIFY_ACCOUNT_SUCCESS',
  VERIFY_ACCOUNT_FAILURE = 'APP/AUTHENTICATION/VERIFY_ACCOUNT_FAILURE',
  
}
