export enum homePageEnum {
  LOAD_DATA_REQUEST = 'APP/HOME_PAGE/LOAD_DATA_REQUEST',
  LOAD_DATA_SUCCESS = 'APP/HOME_PAGE/LOAD_DATA_SUCCESS',
  LOAD_DATA_FAILURE = 'APP/HOME_PAGE/LOAD_DATA_FAILURE',
}
